server.port=80

spring.cloud.gateway.routes[0].id=accounts
spring.cloud.gateway.routes[0].uri=http://account-service:8080
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/v1/accounts/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=2

spring.cloud.gateway.routes[1].id=transactions
spring.cloud.gateway.routes[1].uri=http://transaction-service:8081
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/transactions/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=2
