spring:
  application:
    name: banking-app
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/banking_db}
    username: ${SPRING_DATASOURCE_USERNAME:bank_user}
    password: ${SPRING_DATASOURCE_PASSWORD:bank_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false

server:
  port: 8080

logging:
  level:
    root: INFO
    com.zaxxer.hikari: DEBUG
